using System;

using Microsoft.CodeAnalysis;

using R5T.B0007;

using SyntaxTriviaHelper = Microsoft.CodeAnalysis.CSharp.SyntaxTriviaHelper;

using Instances = R5T.B0007.X002.Instances;


namespace System
{
    public static class ILineIndentationExtensions
    {
        public static SyntaxTriviaList ByTabCount_SyntaxTriviaList(this ILineIndentation _,
            int tabCount)
        {
            var output = Instances.LineIndentationOperator.FromIndentation(
                Instances.Indentation.ByTabCount_SyntaxTriviaList(tabCount));

            return output;
        }

        public static SyntaxTriviaList NewLine_SyntaxTriviaList(this ILineIndentation _)
        {
            var output = new SyntaxTriviaList(
                SyntaxTriviaHelper.NewLine());

            return output;
        }

        public static SyntaxTriviaList BlankLine_SyntaxTriviaList(this ILineIndentation _)
        {
            var newLine = SyntaxTriviaHelper.NewLine();

            // Two blank lines is generated by two new line characters.
            var output = new SyntaxTriviaList(
                newLine,
                newLine);

            return output;
        }

        public static SyntaxTriviaList TwoBlankLines_SyntaxTriviaList(this ILineIndentation _)
        {
            var newLine = SyntaxTriviaHelper.NewLine();

            // Two blank lines is generated by three new line characters.
            var output = new SyntaxTriviaList(
                newLine,
                newLine,
                newLine);

            return output;
        }
    }
}